### ISSUE TITLE
SSL certificate verify failed when using irc3 >=0.9.5

### ISSUE THREAD

**Issue by mattbox** [thomwiggers/onebot#33]
The bot just continues to loop though this on versions of irc3 >=0.9.5 I downgraded to version 0.9.4 and that seemed to fix it. Disabling ssl and using a regular port also works.
```
ERROR irc3.Sol   [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/irc3/__init__.py", line 161, in connection_made
    transport, protocol = f.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 233, in _step
    result = coro.throw(exc)
  File "/usr/lib/python3.4/asyncio/base_events.py", line 588, in create_connection
    sock, protocol_factory, ssl, server_hostname)
  File "/usr/lib/python3.4/asyncio/base_events.py", line 610, in _create_connection_transport
    yield from waiter
  File "/usr/lib/python3.4/asyncio/futures.py", line 388, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 286, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/selector_events.py", line 727, in _on_handshake
    self._sock.do_handshake()
  File "/usr/lib/python3.4/ssl.py", line 804, in do_handshake
    self._sslobj.do_handshake()
```

**Comment by thomwiggers** [comment]
Interesting. I think this is just an irc3 problem, and I should check if there is an option to disable certificate validation.

**Comment by thomwiggers** [comment]
https://github.com/gawel/irc3/blob/4030bc039729c146f65a418133734071f8274152/examples/config.ini#L10

You should specify

    ssl_verify = CERT_NONE
